name: Verify
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  ## Verify module, terraform validate runs only on examples
  verify_module:
    name: Verify module
    strategy:
      matrix:
        terraform: [1.0.9]
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - uses: actions/checkout@v3
      - name: init terraform 
        run: terraform init -get -backend=false -input=false
      - name: check formatting
        run: terraform fmt -recursive -check=true -write=false
